### ISSUE TITLE
Fix notebook dependencies paths

### ISSUE THREAD

**Issue by ruivieira** [trustyai-explainability/trustyai-explainability-python-examples#6]

**Comment by tteofili** [comment]
I think should be resolved as of PR #43 in `trustyai-python/module`

**Comment by ruivieira** [comment]
Hi @tteofili, agreed. I'll change the actual init to simply `trustyai.init()` and mention this issue.

**Comment by tteofili** [comment]
:+1: sounds good, thanks @ruivieira !

**Comment by danielezonca** [comment]
@ruivieira 
I think this issue is outdated and can be closed. Wdyt?
